// Created by CrowbarDecompiler 0.71

$modelname "weapons/c_models/c_heavy_animations.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 18.747 -10.47 -13.398

$cdmaterials "models\weapons\c_models\heavy\c_heavy_viewmodel\"

$cbox 0 0 0 0 0 0

$bbox -24.438 -37.138 -44.72 45.378 74.633 17.923

$definebone "root" "" 0 69.116623 -7.999471 0 0 -161.831101 0 0 0 0 0 0
$definebone "bip_collar_L" "root" 2.131428 -5.80579 -7.194559 -17.630694 -75.555846 -156.575407 0 0 0 0 0 0
$definebone "bip_upperArm_L" "bip_collar_L" -0.000023 -14.061879 0.000002 -32.440701 -48.398946 -17.732527 0 0 0 0 0 0
$definebone "bip_lowerArm_L" "bip_upperArm_L" 0.000004 -17.670918 0.000001 0 -0.000014 -25.322281 0 0 0 0 0 0
$definebone "bip_hand_L" "bip_lowerArm_L" -0.000004 -15.175488 -0.000002 0.000009 -0.000008 0.000018 0 0 0 0 0 0
$definebone "bip_collar_R" "root" -2.13143 -5.805752 -7.194569 17.630692 75.55586 23.424591 0 0 0 0 0 0
$definebone "bip_upperArm_R" "bip_collar_R" -0.000038 14.061868 0.000004 -32.440711 -48.398956 -17.732512 0 0 0 0 0 0
$definebone "bip_lowerArm_R" "bip_upperArm_R" -0.000046 17.670925 0.000008 -0.000003 0.000007 -25.322271 0 0 0 0 0 0
$definebone "bip_hand_R" "bip_lowerArm_R" 0.000019 15.175529 0.000009 -0.000002 -0.000004 -0.000009 0 0 0 0 0 0
$definebone "weapon_bone" "bip_hand_R" 4.498497 6.156168 -2.019428 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "weapon_bone_1" "bip_hand_R" 4.498495 6.692837 -2.019428 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "weapon_bone_2" "bip_hand_R" 4.498497 7.269106 -2.019428 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "weapon_bone_3" "bip_hand_R" 4.498493 7.866358 -2.019429 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "weapon_bone_4" "bip_hand_R" 4.498493 8.630239 -2.019429 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "weapon_bone_L" "bip_hand_L" -4.498003 -6.155987 2.018998 0.000007 -0.00001 0.000013 0 0 0 0 0 0
$definebone "vm_weapon_bone" "bip_hand_R" 5.539101 6.156168 -1.152468 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_1" "bip_hand_R" 5.539099 6.692839 -1.15247 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_2" "bip_hand_R" 5.539101 7.269104 -1.152468 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_3" "bip_hand_R" 5.539099 7.866358 -1.152469 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_4" "bip_hand_R" 5.539101 8.630239 -1.152468 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_5" "bip_hand_R" 5.539101 9.665956 -1.152469 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_6" "bip_hand_R" 5.539101 10.645105 -1.152471 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_7" "bip_hand_R" 5.539101 11.615992 -1.15247 -0.000002 -0.000006 -89.999989 0 0 0 0 0 0
$definebone "vm_weapon_bone_L" "bip_hand_L" -5.39399 -6.155989 0.767102 0.000007 -0.00001 0.000013 0 0 0 0 0 0
$definebone "vm_weapon_bone_1_L" "bip_hand_L" -5.393993 -6.598404 0.767103 0.000007 -0.00001 0.000013 0 0 0 0 0 0
$definebone "vm_weapon_bone_2_L" "bip_hand_L" -5.393986 -7.050543 0.767103 0.000007 -0.00001 0.000013 0 0 0 0 0 0
$definebone "vm_weapon_bone_3_L" "bip_hand_L" -5.39399 -7.654591 0.767104 0.000007 -0.00001 0.000013 0 0 0 0 0 0
$definebone "vm_weapon_bone_4_L" "bip_hand_L" -5.393988 -8.254343 0.767103 0.000007 -0.00001 0.000013 0 0 0 0 0 0
$definebone "effect_hand_L" "bip_hand_L" -3.255001 -3.3283 0.701494 -14.607806 176.613652 -0.398287 0 0 0 0 0 0
$definebone "effect_hand_R" "bip_hand_R" 3.255001 3.328266 -0.701506 14.608245 -3.386359 0.398431 0 0 0 0 0 0
$definebone "bip_thumb_0_L" "bip_hand_L" -2.440094 -1.974152 3.836563 11.662863 -29.680054 -44.861311 0 0 0 0 0 0
$definebone "bip_thumb_0_R" "bip_hand_R" 2.440136 1.974119 -3.83659 11.662859 -29.680054 -44.861335 0 0 0 0 0 0
$definebone "bip_thumb_1_L" "bip_thumb_0_L" 0.000001 -4.365019 -0.000004 0.000007 0.000003 27.712584 0 0 0 0 0 0
$definebone "bip_thumb_1_R" "bip_thumb_0_R" -0.00006 4.365004 -0.000011 -0.000004 -0.000009 27.712564 0 0 0 0 0 0
$definebone "bip_thumb_2_L" "bip_thumb_1_L" 0 -1.793211 -0.000006 -0.000001 -0.000007 -17.637265 0 0 0 0 0 0
$definebone "bip_thumb_2_R" "bip_thumb_1_R" 0.000001 1.793217 0.000013 -0.000003 -0.000003 -17.63727 0 0 0 0 0 0
$definebone "bip_index_0_L" "bip_hand_L" -0.751591 -6.859724 4.600632 77.620947 163.772432 172.636692 0 0 0 0 0 0
$definebone "bip_index_0_R" "bip_hand_R" 0.751553 6.859684 -4.600655 77.620947 163.772445 172.636788 0 0 0 0 0 0
$definebone "bip_index_1_L" "bip_index_0_L" 0.000004 -3.600685 0.000002 -0.000002 -0.000016 53.65174 0 0 0 0 0 0
$definebone "bip_index_1_R" "bip_index_0_R" 0.000008 3.600672 0.000046 0.000015 0.000013 53.651734 0 0 0 0 0 0
$definebone "bip_index_2_L" "bip_index_1_L" -0.000002 -2.262768 -0.000002 -0.000009 -0.000006 4.468373 0 0 0 0 0 0
$definebone "bip_index_2_R" "bip_index_1_R" -0.000017 2.262806 -0.000048 0.000009 -0.000004 4.468373 0 0 0 0 0 0
$definebone "bip_middle_0_L" "bip_hand_L" -0.713047 -6.783436 1.947195 68.239156 155.918548 177.16269 0 0 0 0 0 0
$definebone "bip_middle_0_R" "bip_hand_R" 0.713024 6.783401 -1.947211 68.239184 155.918561 177.162758 0 0 0 0 0 0
$definebone "bip_middle_1_L" "bip_middle_0_L" 0.040714 -4.737331 -0.016134 -0.000007 -0.000022 47.021058 0 0 0 0 0 0
$definebone "bip_middle_1_R" "bip_middle_0_R" 0.000013 4.72975 0.000051 0.000012 0.000006 47.021071 0 0 0 0 0 0
$definebone "bip_middle_2_L" "bip_middle_1_L" 0 -2.758442 -0.000002 0 -0.000001 5.248346 0 0 0 0 0 0
$definebone "bip_middle_2_R" "bip_middle_1_R" -0.000004 2.75845 0.000022 0.000003 -0.000001 5.248326 0 0 0 0 0 0
$definebone "bip_ring_0_L" "bip_hand_L" -1.681087 -6.576651 -0.639792 65.725756 156.981926 -178.818382 0 0 0 0 0 0
$definebone "bip_ring_0_R" "bip_hand_R" 1.681068 6.576639 0.639779 65.725736 156.981967 -178.8183 0 0 0 0 0 0
$definebone "bip_ring_1_L" "bip_ring_0_L" -0.000002 -3.781096 -0.000004 -0.000005 -0.000028 34.561536 0 0 0 0 0 0
$definebone "bip_ring_1_R" "bip_ring_0_R" 0.000005 3.781063 0.000031 -0.00001 0.000008 34.561515 0 0 0 0 0 0
$definebone "bip_ring_2_L" "bip_ring_1_L" 0 -2.398426 -0.000007 0.000006 -0.000017 16.826311 0 0 0 0 0 0
$definebone "bip_ring_2_R" "bip_ring_1_R" 0.000011 2.398407 0.000017 0.000008 -0.000001 16.826289 0 0 0 0 0 0
$definebone "bip_pinky_0_L" "bip_hand_L" -2.639706 -6.552818 -2.641662 58.305363 139.782103 169.755773 0 0 0 0 0 0
$definebone "bip_pinky_0_R" "bip_hand_R" 2.639748 6.552765 2.641619 58.305357 139.782089 169.755732 0 0 0 0 0 0
$definebone "bip_pinky_1_L" "bip_pinky_0_L" 0.000001 -3.015034 -0.000005 0.000018 0.000005 31.245431 0 0 0 0 0 0
$definebone "bip_pinky_1_R" "bip_pinky_0_R" 0.000008 3.015026 -0.000034 0.000013 -0.000002 31.245431 0 0 0 0 0 0
$definebone "bip_pinky_2_L" "bip_pinky_1_L" -0.000001 -1.878258 -0.000002 0.000003 -0.000005 20.546888 0 0 0 0 0 0
$definebone "bip_pinky_2_R" "bip_pinky_1_R" 0.000003 1.878239 -0.000029 -0.000001 -0.000003 20.546908 0 0 0 0 0 0


$sectionframes 30 120

$poseparameter "r_hand_grip" 0 12 loop 0

$weightlist "weights_r_handposes" {
	 "root" 0
	 "bip_collar_L" 0
	 "bip_upperArm_L" 0
	 "bip_lowerArm_L" 0
	 "bip_hand_L" 0
	 "bip_collar_R" 0
	 "bip_upperArm_R" 0
	 "bip_lowerArm_R" 0
	 "bip_hand_R" 0
	 "weapon_bone" 1
	 "weapon_bone_1" 0
	 "weapon_bone_2" 0
	 "weapon_bone_3" 0
	 "weapon_bone_4" 0
	 "weapon_bone_L" 0
	 "vm_weapon_bone" 1
	 "vm_weapon_bone_1" 1
	 "vm_weapon_bone_2" 1
	 "vm_weapon_bone_3" 1
	 "vm_weapon_bone_4" 1
	 "vm_weapon_bone_5" 1
	 "vm_weapon_bone_6" 1
	 "vm_weapon_bone_7" 1
	 "vm_weapon_bone_L" 0
	 "vm_weapon_bone_1_L" 0
	 "vm_weapon_bone_2_L" 0
	 "vm_weapon_bone_3_L" 0
	 "vm_weapon_bone_4_L" 0
	 "effect_hand_L" 0
	 "effect_hand_R" 0
	 "bip_thumb_0_L" 0
	 "bip_thumb_0_R" 1
	 "bip_thumb_1_L" 0
	 "bip_thumb_1_R" 1
	 "bip_thumb_2_L" 0
	 "bip_thumb_2_R" 1
	 "bip_index_0_L" 0
	 "bip_index_0_R" 1
	 "bip_index_1_L" 0
	 "bip_index_1_R" 1
	 "bip_index_2_L" 0
	 "bip_index_2_R" 1
	 "bip_middle_0_L" 0
	 "bip_middle_0_R" 1
	 "bip_middle_1_L" 0
	 "bip_middle_1_R" 1
	 "bip_middle_2_L" 0
	 "bip_middle_2_R" 1
	 "bip_ring_0_L" 0
	 "bip_ring_0_R" 1
	 "bip_ring_1_L" 0
	 "bip_ring_1_R" 1
	 "bip_ring_2_L" 0
	 "bip_ring_2_R" 1
	 "bip_pinky_0_L" 0
	 "bip_pinky_0_R" 1
	 "bip_pinky_1_L" 0
	 "bip_pinky_1_R" 1
	 "bip_pinky_2_L" 0
	 "bip_pinky_2_R" 1
}

$animation "saxxy_pose" "c_heavy_animations_anims\saxxy_pose.smd" {
	fps 30
	loop
	weightlist "weights_r_handposes"
}

$animation "bread_bagged_pose" "c_heavy_animations_anims\bread_bagged_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_baguette_pose" "c_heavy_animations_anims\bread_baguette_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_burnt_pose" "c_heavy_animations_anims\bread_burnt_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_cinnamon_pose" "c_heavy_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_cornbread_pose" "c_heavy_animations_anims\bread_cornbread_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_crumpet_pose" "c_heavy_animations_anims\bread_crumpet_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_pretzel_pose" "c_heavy_animations_anims\bread_pretzel_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_ration_pose" "c_heavy_animations_anims\bread_ration_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_robo_pose" "c_heavy_animations_anims\bread_robo_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_russianblack_pose" "c_heavy_animations_anims\bread_russianblack_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_shortbread_pose" "c_heavy_animations_anims\bread_shortbread_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "breadmonster" "c_heavy_animations_anims\breadmonster.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"breadmonster"
	blend "r_hand_grip" 0 12
	blendwidth 13
	{ event AE_CL__PLAYSOUND 4 "Weapon_bm_throwable.growl" }
	{ event AE_CL__PLAYSOUND 83 "Weapon_bm_throwable.grunt" }
	{ event AE_CL__PLAYSOUND 83 "Weapon_bm_throwable.grunt" }
	{ event AE_CL__PLAYSOUND 125 "Weapon_bm_throwable.grunt" }
	{ event AE_CL__PLAYSOUND 133 "Weapon_bm_throwable.grunt" }
	fadein 0.2
	fadeout 0.2
	hidden
	realtime
}

$sequence "sw_draw" {
	"c_heavy_animations_anims\sw_draw.smd"
	activity "ACT_ITEM1_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "sw_idle" {
	"c_heavy_animations_anims\sw_idle.smd"
	activity "ACT_ITEM1_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "f_swing_left" {
	"c_heavy_animations_anims\f_swing_left.smd"
	activity "ACT_FISTS_VM_HITLEFT" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "f_swing_right" {
	"c_heavy_animations_anims\f_swing_right.smd"
	activity "ACT_FISTS_VM_HITRIGHT" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "f_swing_crit" {
	"c_heavy_animations_anims\f_swing_crit.smd"
	activity "ACT_FISTS_VM_SWINGHARD" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "f_idle" {
	"c_heavy_animations_anims\f_idle.smd"
	activity "ACT_FISTS_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
}

$sequence "f_draw" {
	"c_heavy_animations_anims\f_draw.smd"
	activity "ACT_FISTS_VM_DRAW" 1
	{ event 5004 1 "Weapon_Fist.Draw" }
	{ event 5004 5 "Weapon_Fist.HitHand" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "bg_metal_draw" {
	"c_heavy_animations_anims\bg_metal_draw.smd"
	activity "ACT_MELEE_VM_ITEM1_DRAW" 1
	{ event 5004 1 "Weapon_Fist.Draw" }
	{ event 5004 3 "Weapon_MetalGloves.HitGlove" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "bg_swing_left" {
	"c_heavy_animations_anims\bg_swing_left.smd"
	activity "ACT_VM_HITLEFT" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "bg_swing_right" {
	"c_heavy_animations_anims\bg_swing_right.smd"
	activity "ACT_VM_HITRIGHT" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "bg_swing_crit" {
	"c_heavy_animations_anims\bg_swing_crit.smd"
	activity "ACT_MELEE_VM_SWINGHARD" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "bg_idle" {
	"c_heavy_animations_anims\bg_idle.smd"
	activity "ACT_MELEE_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
}

$sequence "bg_draw" {
	"c_heavy_animations_anims\bg_draw.smd"
	activity "ACT_MELEE_VM_DRAW" 1
	{ event 5004 1 "Weapon_Fist.Draw" }
	{ event 5004 3 "Weapon_BoxingGLoves.HitGlove" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "draw" {
	"c_heavy_animations_anims\draw.smd"
	activity "ACT_SECONDARY_VM_DRAW" 1
	{ event 5004 1 "Weapon_Shotgun.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "idle" {
	"c_heavy_animations_anims\idle.smd"
	activity "ACT_SECONDARY_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "fire" {
	"c_heavy_animations_anims\fire.smd"
	activity "ACT_SECONDARY_VM_PRIMARYATTACK" 1
	{ event 5004 9 "Weapon_ShotgunEngineer.Cock_Back" }
	{ event 5004 13 "Weapon_ShotgunEngineer.Cock_Forward" }
	{ event 6002 13 "2" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "reload_start" {
	"c_heavy_animations_anims\reload_start.smd"
	activity "ACT_SECONDARY_RELOAD_START" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "reload_loop" {
	"c_heavy_animations_anims\reload_loop.smd"
	activity "ACT_SECONDARY_VM_RELOAD" 1
	{ event 5004 2 "Weapon_Shotgun.Reload" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "reload_end" {
	"c_heavy_animations_anims\reload_end.smd"
	activity "ACT_SECONDARY_RELOAD_FINISH" 1
	{ event 5004 10 "Weapon_ShotgunEngineer.Cock_Back" }
	{ event 5004 15 "Weapon_ShotgunEngineer.Cock_Forward" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 35
}

$sequence "m_idle" {
	"c_heavy_animations_anims\m_idle.smd"
	activity "ACT_PRIMARY_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "m_fire" {
	"c_heavy_animations_anims\m_fire.smd"
	activity "ACT_PRIMARY_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
	loop
}

$sequence "m_spool_up" {
	"c_heavy_animations_anims\m_spool_up.smd"
	activity "ACT_PRIMARY_ATTACK_STAND_PREFIRE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "m_spool_down" {
	"c_heavy_animations_anims\m_spool_down.smd"
	activity "ACT_PRIMARY_ATTACK_STAND_POSTFIRE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "m_draw" {
	"c_heavy_animations_anims\m_draw.smd"
	activity "ACT_PRIMARY_VM_DRAW" 1
	{ event 5004 1 "Weapon_Minigun.Draw" }
	fadein 0.2
	fadeout 0.2
	transition "lowered" "raised"
	snap
	fps 30
}

$sequence "m_spool_idle" {
	"c_heavy_animations_anims\m_spool_idle.smd"
	activity "ACT_PRIMARY_VM_SECONDARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
	loop
}

$sequence "melee_allclass_draw" {
	"c_heavy_animations_anims\melee_allclass_draw.smd"
	activity "ACT_MELEE_ALLCLASS_VM_DRAW" 1
	{ event 5004 1 "Weapon_Machete.Draw" }
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	snap
	fps 30
}

$sequence "melee_allclass_idle" {
	"c_heavy_animations_anims\melee_allclass_idle.smd"
	activity "ACT_MELEE_ALLCLASS_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "melee_allclass_swing" {
	"c_heavy_animations_anims\melee_allclass_swing.smd"
	activity "ACT_MELEE_ALLCLASS_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "throw_draw" {
	"c_heavy_animations_anims\throw_draw.smd"
	activity "ACT_THROWABLE_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	snap
	fps 30
}

$sequence "throw_idle" {
	"c_heavy_animations_anims\throw_idle.smd"
	activity "ACT_THROWABLE_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	fps 30
	loop
}

$sequence "throw_fire" {
	"c_heavy_animations_anims\throw_fire.smd"
	activity "ACT_THROWABLE_VM_FIRE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	snap
	fps 30
}

$sequence "spell_draw" {
	"c_heavy_animations_anims\spell_draw.smd"
	activity "ACT_SPELL_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "spell_fire" {
	"c_heavy_animations_anims\spell_fire.smd"
	activity "ACT_SPELL_VM_FIRE" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "breadglove_swing_left" {
	"c_heavy_animations_anims\breadglove_swing_left.smd"
	activity "ACT_BREADGLOVES_VM_HITLEFT" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "breadglove_swing_right" {
	"c_heavy_animations_anims\breadglove_swing_right.smd"
	activity "ACT_BREADGLOVES_VM_HITRIGHT" 1
	{ event AE_CL_PLAYSOUND 0 "Weapon_bm_gloves.attack" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "breadglove_swing_crit" {
	"c_heavy_animations_anims\breadglove_swing_crit.smd"
	activity "ACT_BREADGLOVES_VM_SWINGHARD" 1
	{ event AE_CL_PLAYSOUND 0 "Weapon_bm_gloves.attack" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "breadglove_idle_A" {
	"c_heavy_animations_anims\breadglove_idle_A.smd"
	activity "ACT_BREADGLOVES_VM_IDLE" 2
	{ event AE_CL_PLAYSOUND 2 "Weapon_bm_gloves.snap" }
	{ event AE_CL_PLAYSOUND 25 "Weapon_bm_gloves.scream" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
}

$sequence "breadglove_idle_B" {
	"c_heavy_animations_anims\breadglove_idle_B.smd"
	activity "ACT_BREADGLOVES_VM_IDLE" 4
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "breadglove_idle_C" {
	"c_heavy_animations_anims\breadglove_idle_C.smd"
	activity "ACT_BREADGLOVES_VM_IDLE" 1
	{ event AE_CL_PLAYSOUND 2 "Weapon_bm_gloves.snap" }
	{ event AE_CL_PLAYSOUND 47 "Weapon_bm_gloves.snap" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 25
}

$sequence "breadglove_draw_A" {
	"c_heavy_animations_anims\breadglove_draw_A.smd"
	activity "ACT_BREADGLOVES_VM_DRAW" 1
	{ event AE_CL_PLAYSOUND 2 "Weapon_bm_gloves.snap" }
	{ event AE_CL_PLAYSOUND 25 "Weapon_bm_gloves.scream" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "breadglove_draw_B" {
	"c_heavy_animations_anims\breadglove_draw_B.smd"
	activity "ACT_BREADGLOVES_VM_DRAW" 1
	{ event AE_CL_PLAYSOUND 2 "Weapon_bm_gloves.snap" }
	{ event AE_CL_PLAYSOUND 47 "Weapon_bm_gloves.snap" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "primary_inspect_start" {
	"c_heavy_animations_anims\primary_inspect_start.smd"
	activity "ACT_PRIMARY_VM_INSPECT_START" 1
	{ event 5004 3 "WeaponInspect.Movement1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "primary_inspect_idle" {
	"c_heavy_animations_anims\primary_inspect_idle.smd"
	activity "ACT_PRIMARY_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "primary_inspect_end" {
	"c_heavy_animations_anims\primary_inspect_end.smd"
	activity "ACT_PRIMARY_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement3" }
	{ event 5004 84 "WeaponInspect.Movement1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "secondary_inspect_start" {
	"c_heavy_animations_anims\secondary_inspect_start.smd"
	activity "ACT_SECONDARY_VM_INSPECT_START" 1
	{ event 5004 3 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 35
}

$sequence "secondary_inspect_idle" {
	"c_heavy_animations_anims\secondary_inspect_idle.smd"
	activity "ACT_SECONDARY_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "secondary_inspect_end" {
	"c_heavy_animations_anims\secondary_inspect_end.smd"
	activity "ACT_SECONDARY_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement2" }
	{ event 5004 94 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "melee_allclass_inspect_start" {
	"c_heavy_animations_anims\melee_allclass_inspect_start.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
}

$sequence "melee_allclass_inspect_idle" {
	"c_heavy_animations_anims\melee_allclass_inspect_idle.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "melee_allclass_inspect_end" {
	"c_heavy_animations_anims\melee_allclass_inspect_end.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_END" 1
	{ event 5004 4 "WeaponInspect.Movement3" }
	{ event 5004 70 "WeaponInspect.Movement2" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "item1_inspect_start" {
	"c_heavy_animations_anims\item1_inspect_start.smd"
	activity "ACT_ITEM1_VM_INSPECT_START" 1
	{ event 5004 1 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 24
}

$sequence "item1_inspect_idle" {
	"c_heavy_animations_anims\item1_inspect_idle.smd"
	activity "ACT_ITEM1_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 24
	loop
}

$sequence "item1_inspect_end" {
	"c_heavy_animations_anims\item1_inspect_end.smd"
	activity "ACT_ITEM1_VM_INSPECT_END" 1
	{ event 5004 1 "MeleeInspect.Movement" }
	{ event 5004 63 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 24
}

$sequence "melee_inspect_start" {
	"c_heavy_animations_anims\melee_inspect_start.smd"
	activity "ACT_MELEE_VM_INSPECT_START" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "melee_inspect_idle" {
	"c_heavy_animations_anims\melee_inspect_idle.smd"
	activity "ACT_MELEE_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "melee_inspect_end" {
	"c_heavy_animations_anims\melee_inspect_end.smd"
	activity "ACT_MELEE_VM_INSPECT_END" 1
	{ event 5004 80 "MeleeInspect.Movement" }
	{ event 5004 93 "MeleeInspect.Movement" }
	{ event 5004 100 "MeleeInspect.Movement" }
	{ event 5004 106 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Alt1_inspect_start" {
	"c_heavy_animations_anims\Alt1_inspect_start.smd"
	activity "ACT_MELEE_ALT1_VM_INSPECT_START" 1
	{ event 5004 4 "MeleeInspect.Movement" }
	{ event 5004 46 "MeleeInspect.Movement" }
	{ event 5004 55 "MeleeInspect.Movement" }
	{ event 5004 60 "MeleeInspect.Movement" }
	{ event 5004 65 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Alt1_inspect_idle" {
	"c_heavy_animations_anims\Alt1_inspect_idle.smd"
	activity "ACT_MELEE_ALT1_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Alt1_inspect_end" {
	"c_heavy_animations_anims\Alt1_inspect_end.smd"
	activity "ACT_MELEE_ALT1_VM_INSPECT_END" 1
	{ event 5004 57 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Alt2_inspect_start" {
	"c_heavy_animations_anims\Alt2_inspect_start.smd"
	activity "ACT_MELEE_ALT2_VM_INSPECT_START" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Alt2_inspect_idle" {
	"c_heavy_animations_anims\Alt2_inspect_idle.smd"
	activity "ACT_MELEE_ALT2_VM_INSPECT_IDLE" 1
	{ event 5004 19 "Weapon_bm_gloves.attack" }
	{ event 5004 48 "Weapon_bm_throwable.growl" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Alt2_inspect_end" {
	"c_heavy_animations_anims\Alt2_inspect_end.smd"
	activity "ACT_MELEE_ALT2_VM_INSPECT_END" 1
	{ event 5004 6 "Weapon_bm_gloves.attack" }
	{ event 5004 24 "Weapon_bm_throwable.growl" }
	{ event 5004 47 "Weapon_bm_gloves.snap" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Alt3_inspect_start" {
	"c_heavy_animations_anims\Alt3_inspect_start.smd"
	activity "ACT_MELEE_ALT3_VM_INSPECT_START" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Alt3_inspect_idle" {
	"c_heavy_animations_anims\Alt3_inspect_idle.smd"
	activity "ACT_MELEE_ALT3_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Alt3_inspect_end" {
	"c_heavy_animations_anims\Alt3_inspect_end.smd"
	activity "ACT_MELEE_ALT3_VM_INSPECT_END" 1
	{ event 5004 80 "MeleeInspect.Movement" }
	{ event 5004 93 "MeleeInspect.Movement" }
	{ event 5004 100 "MeleeInspect.Movement" }
	{ event 5004 104 "MeleeInspect.Movement" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "grapple_draw" {
	"c_heavy_animations_anims\grapple_draw.smd"
	activity "ACT_GRAPPLE_DRAW" 1
	{ event AE_CL_PLAYSOUND 1 "WeaponGrapplingHook.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "grapple_idle" {
	"c_heavy_animations_anims\grapple_idle.smd"
	activity "ACT_GRAPPLE_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "grapple_fire_start" {
	"c_heavy_animations_anims\grapple_fire_start.smd"
	activity "ACT_GRAPPLE_FIRE_START" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "grapple_fire_idle" {
	"c_heavy_animations_anims\grapple_fire_idle.smd"
	activity "ACT_GRAPPLE_FIRE_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "grapple_pull_start" {
	"c_heavy_animations_anims\grapple_pull_start.smd"
	activity "ACT_GRAPPLE_PULL_START" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "grapple_pull_idle" {
	"c_heavy_animations_anims\grapple_pull_idle.smd"
	activity "ACT_GRAPPLE_PULL_IDLE" 1
	fadein 0.1
	fadeout 0.2
	fps 30
	loop
}

$sequence "grapple_pull_end" {
	"c_heavy_animations_anims\grapple_pull_end.smd"
	activity "ACT_GRAPPLE_PULL_END" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_pickup" {
	"c_heavy_animations_anims\PASSTIME_ball_pickup.smd"
	activity "ACT_BALL_VM_PICKUP" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_idle" {
	"c_heavy_animations_anims\PASSTIME_ball_idle.smd"
	activity "ACT_BALL_VM_IDLE" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_catch1" {
	"c_heavy_animations_anims\PASSTIME_ball_catch1.smd"
	activity "ACT_BALL_VM_CATCH" 100
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_catch2" {
	"c_heavy_animations_anims\PASSTIME_ball_catch2.smd"
	activity "ACT_BALL_VM_CATCH" 1
	{ event AE_CL_PLAYSOUND 0 "Heavy.Award09" }
	{ event AE_CL_PLAYSOUND 115 "Canister.ImpactHard" }
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_end" {
	"c_heavy_animations_anims\PASSTIME_ball_throw_end.smd"
	activity "ACT_BALL_VM_THROW_END" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_start" {
	"c_heavy_animations_anims\PASSTIME_ball_throw_start.smd"
	activity "ACT_BALL_VM_THROW_start" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_loop" {
	"c_heavy_animations_anims\PASSTIME_ball_throw_loop.smd"
	activity "ACT_BALL_VM_THROW_LOOP" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}
