// Created by CrowbarDecompiler 0.71

$modelname "weapons\c_models\c_pyro_animations.mdl"

$surfaceprop "default"

$contents "solid"

$illumposition 23.948 -14.345 -14.582

$cdmaterials "models\weapons\c_models\pyro\c_pyro_viewmodel\"

$cbox 0 0 0 0 0 0

$bbox -18.527 -22.679 -35.393 47.216 70.575 6.23

$definebone "root" "" 0 70.5746 1.21084 0 0 0 0 0 0 0 0 0
$definebone "bip_collar_L" "root" 1.305631 0 0.654511 3.721619 73.951414 28.539522 0 0 0 0 0 0
$definebone "bip_collar_R" "root" -1.30563 0 0.65451 -3.721619 -73.951414 -151.460483 0 0 0 0 0 0
$definebone "bip_upperArm_L" "bip_collar_L" -0.000015 -8.747574 0 -18.948367 -47.089636 -16.014705 0 0 0 0 0 0
$definebone "bip_upperArm_R" "bip_collar_R" -0.000015 8.747572 0 -18.94836 -47.089622 -16.014716 0 0 0 0 0 0
$definebone "bip_lowerArm_L" "bip_upperArm_L" 0.000004 -12.789986 -0.000001 0.000003 -0.00001 -17.920094 0 0 0 0 0 0
$definebone "bip_lowerArm_R" "bip_upperArm_R" 0.000031 12.789986 0 -0.000001 -0.000007 -17.920089 0 0 0 0 0 0
$definebone "bip_hand_L" "bip_lowerArm_L" 0 -11.535656 -0.000005 0.000005 -0.000007 0.000004 0 0 0 0 0 0
$definebone "bip_hand_R" "bip_lowerArm_R" -0.000019 11.535679 0.000011 0 0.000003 -0.000004 0 0 0 0 0 0
$definebone "effect_hand_L" "bip_hand_L" -1.973114 -3.060043 -0.496675 -3.577047 167.34611 4.718673 0 0 0 0 0 0
$definebone "effect_hand_R" "bip_hand_R" 1.973125 3.060036 0.496675 3.577485 -12.65394 -4.71851 0 0 0 0 0 0
$definebone "vm_weapon_bone" "bip_hand_R" 2.988033 5.244392 0.161969 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_1" "bip_hand_R" 3.32021 5.952023 0.419589 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_2" "bip_hand_R" 3.786766 6.945927 0.781427 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_3" "bip_hand_R" 4.215763 7.859806 1.114133 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_4" "bip_hand_R" 4.801836 9.108303 1.568659 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_5" "bip_hand_R" 5.491838 10.578205 2.103789 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_6" "bip_hand_R" 6.138348 11.955448 2.605187 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_7" "bip_hand_R" 6.642494 13.029421 2.996177 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "vm_weapon_bone_L" "bip_hand_L" -4.215206 -4.69171 -0.097744 2.731968 -24.245343 108.261388 0 0 0 0 0 0
$definebone "vm_weapon_bone_L_1" "bip_hand_L" -4.829796 -6.00095 -0.574386 2.731968 -24.245343 108.261388 0 0 0 0 0 0
$definebone "vm_weapon_bone_L_2" "bip_hand_L" -5.357635 -7.125397 -0.983751 2.731968 -24.245343 108.261388 0 0 0 0 0 0
$definebone "weapon_bone" "bip_hand_R" 2.227039 5.587126 0.201796 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "weapon_bone_1" "bip_hand_R" 2.227039 5.587126 0.201796 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "weapon_bone_2" "bip_hand_R" 2.227039 5.587126 0.201796 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "weapon_bone_3" "bip_hand_R" 2.227039 5.587126 0.201796 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "weapon_bone_4" "bip_hand_R" 2.227039 5.587126 0.201796 2.731958 -24.245331 -71.738624 0 0 0 0 0 0
$definebone "weapon_bone_L" "bip_hand_L" -2.227024 -5.587128 -0.201794 2.731968 -24.245343 108.261388 0 0 0 0 0 0
$definebone "bip_thumb_0_L" "bip_hand_L" -1.533504 -2.157135 2.270475 3.922325 -26.79105 -11.219357 0 0 0 0 0 0
$definebone "bip_thumb_0_R" "bip_hand_R" 1.533531 2.157104 -2.270484 3.922318 -26.791038 -11.219363 0 0 0 0 0 0
$definebone "bip_thumb_1_L" "bip_thumb_0_L" 0.000003 -2.788845 0 0.000006 -0.00001 2.10903 0 0 0 0 0 0
$definebone "bip_thumb_1_R" "bip_thumb_0_R" -0.000025 2.788849 -0.000006 -0.000002 -0.000001 2.109022 0 0 0 0 0 0
$definebone "bip_thumb_2_L" "bip_thumb_1_L" -0.000003 -1.626434 0.000002 0.000005 -0.00001 -17.536779 0 0 0 0 0 0
$definebone "bip_thumb_2_R" "bip_thumb_1_R" -0.000021 1.626461 0.000015 -0.000002 -0.000001 -17.536777 0 0 0 0 0 0
$definebone "bip_index_0_L" "bip_hand_L" -0.224178 -6.146786 2.425699 80.7422 64.177687 88.726186 0 0 0 0 0 0
$definebone "bip_index_0_R" "bip_hand_R" 0.224171 6.146811 -2.425689 80.742227 64.177762 88.726165 0 0 0 0 0 0
$definebone "bip_index_1_L" "bip_index_0_L" -0.000002 -2.470013 0.000004 -0.000003 -0.000004 42.537284 0 0 0 0 0 0
$definebone "bip_index_1_R" "bip_index_0_R" 0.000023 2.46994 0.000065 -0.000007 0.000004 42.537353 0 0 0 0 0 0
$definebone "bip_index_2_L" "bip_index_1_L" 0.000001 -1.775543 0 -0.000003 0 -1.947477 0 0 0 0 0 0
$definebone "bip_index_2_R" "bip_index_1_R" -0.000003 1.775558 -0.000022 0.000003 0.000003 -1.947491 0 0 0 0 0 0
$definebone "bip_middle_0_L" "bip_hand_L" -0.335812 -5.901419 0.441528 79.201979 101.200919 120.359408 0 0 0 0 0 0
$definebone "bip_middle_0_R" "bip_hand_R" 0.335846 5.901382 -0.441533 79.201965 101.200994 120.35949 0 0 0 0 0 0
$definebone "bip_middle_1_L" "bip_middle_0_L" 0.000001 -2.973972 0 0.000004 0 52.877682 0 0 0 0 0 0
$definebone "bip_middle_1_R" "bip_middle_0_R" 0.000002 2.97403 -0.000013 -0.000007 0.000009 52.877754 0 0 0 0 0 0
$definebone "bip_middle_2_L" "bip_middle_1_L" -0.000004 -2.194397 -0.000001 -0.000007 0.000003 13.190779 0 0 0 0 0 0
$definebone "bip_middle_2_R" "bip_middle_1_R" 0.00001 2.19437 0.000061 -0.000001 0.000007 13.190686 0 0 0 0 0 0
$definebone "bip_ring_0_L" "bip_hand_L" -0.681835 -5.259802 -1.23648 75.007874 113.805356 129.596569 0 0 0 0 0 0
$definebone "bip_ring_0_R" "bip_hand_R" 0.68185 5.259848 1.236489 75.007874 113.805356 129.596597 0 0 0 0 0 0
$definebone "bip_ring_1_L" "bip_ring_0_L" -0.000001 -2.601486 0.000002 0.000002 -0.000006 52.884304 0 0 0 0 0 0
$definebone "bip_ring_1_R" "bip_ring_0_R" 0.000008 2.601433 -0.000053 0.000001 -0.000002 52.884345 0 0 0 0 0 0
$definebone "bip_ring_2_L" "bip_ring_1_L" 0.000001 -1.651787 0.000004 -0.000003 0.000008 3.940939 0 0 0 0 0 0
$definebone "bip_ring_2_R" "bip_ring_1_R" -0.000015 1.651848 -0.000021 0 0.000012 3.940849 0 0 0 0 0 0
$definebone "bip_pinky_0_L" "bip_hand_L" -0.761402 -4.8223 -2.782144 66.224913 113.492746 137.016422 0 0 0 0 0 0
$definebone "bip_pinky_0_R" "bip_hand_R" 0.761452 4.822269 2.782139 66.224927 113.492705 137.016381 0 0 0 0 0 0
$definebone "bip_pinky_1_L" "bip_pinky_0_L" -0.000001 -2.219696 0.000006 0 0.00001 48.093575 0 0 0 0 0 0
$definebone "bip_pinky_1_R" "bip_pinky_0_R" 0.000008 2.219704 -0.000032 0.000007 0.000008 48.093582 0 0 0 0 0 0
$definebone "bip_pinky_2_L" "bip_pinky_1_L" 0 -1.372696 0 0.000003 0.000001 -0.780228 0 0 0 0 0 0
$definebone "bip_pinky_2_R" "bip_pinky_1_R" 0.000003 1.372696 -0.000017 0.000003 -0.000001 -0.78023 0 0 0 0 0 0


$sectionframes 30 121

$poseparameter "r_hand_grip" 0 12 loop 0

$weightlist "weights_r_handposes" {
	 "root" 0
	 "bip_collar_L" 0
	 "bip_collar_R" 0
	 "bip_upperArm_L" 0
	 "bip_upperArm_R" 0
	 "bip_lowerArm_L" 0
	 "bip_lowerArm_R" 0
	 "bip_hand_L" 0
	 "bip_hand_R" 0
	 "effect_hand_L" 0
	 "effect_hand_R" 0
	 "vm_weapon_bone" 1
	 "vm_weapon_bone_1" 1
	 "vm_weapon_bone_2" 1
	 "vm_weapon_bone_3" 1
	 "vm_weapon_bone_4" 1
	 "vm_weapon_bone_5" 1
	 "vm_weapon_bone_6" 1
	 "vm_weapon_bone_7" 1
	 "vm_weapon_bone_L" 0
	 "vm_weapon_bone_L_1" 0
	 "vm_weapon_bone_L_2" 0
	 "weapon_bone" 1
	 "weapon_bone_1" 0
	 "weapon_bone_2" 0
	 "weapon_bone_3" 0
	 "weapon_bone_4" 0
	 "weapon_bone_L" 0
	 "bip_thumb_0_L" 0
	 "bip_thumb_0_R" 1
	 "bip_thumb_1_L" 0
	 "bip_thumb_1_R" 1
	 "bip_thumb_2_L" 0
	 "bip_thumb_2_R" 1
	 "bip_index_0_L" 0
	 "bip_index_0_R" 1
	 "bip_index_1_L" 0
	 "bip_index_1_R" 1
	 "bip_index_2_L" 0
	 "bip_index_2_R" 1
	 "bip_middle_0_L" 0
	 "bip_middle_0_R" 1
	 "bip_middle_1_L" 0
	 "bip_middle_1_R" 1
	 "bip_middle_2_L" 0
	 "bip_middle_2_R" 1
	 "bip_ring_0_L" 0
	 "bip_ring_0_R" 1
	 "bip_ring_1_L" 0
	 "bip_ring_1_R" 1
	 "bip_ring_2_L" 0
	 "bip_ring_2_R" 1
	 "bip_pinky_0_L" 0
	 "bip_pinky_0_R" 1
	 "bip_pinky_1_L" 0
	 "bip_pinky_1_R" 1
	 "bip_pinky_2_L" 0
	 "bip_pinky_2_R" 1
}

$animation "saxxy_pose" "c_pyro_animations_anims\saxxy_pose.smd" {
	fps 30
	loop
	weightlist "weights_r_handposes"
}

$animation "bread_bagged_pose" "c_pyro_animations_anims\bread_bagged_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_baguette_pose" "c_pyro_animations_anims\bread_baguette_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_burnt_pose" "c_pyro_animations_anims\bread_burnt_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_cinnamon_pose" "c_pyro_animations_anims\bread_cinnamon_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_cornbread_pose" "c_pyro_animations_anims\bread_cornbread_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_crumpet_pose" "c_pyro_animations_anims\bread_crumpet_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_pretzel_pose" "c_pyro_animations_anims\bread_pretzel_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_ration_pose" "c_pyro_animations_anims\bread_ration_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_robo_pose" "c_pyro_animations_anims\bread_robo_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_russianblack_pose" "c_pyro_animations_anims\bread_russianblack_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "bread_shortbread_pose" "c_pyro_animations_anims\bread_shortbread_pose.smd" {
	fps 30
	weightlist "weights_r_handposes"
}

$animation "breadmonster" "c_pyro_animations_anims\breadmonster.smd" {
	fps 30
	loop
	weightlist "weights_r_handposes"
}

$sequence "r_handposes" {
	"saxxy_pose"
	"bread_bagged_pose"
	"bread_baguette_pose"
	"bread_burnt_pose"
	"bread_cinnamon_pose"
	"bread_cornbread_pose"
	"bread_crumpet_pose"
	"bread_pretzel_pose"
	"bread_ration_pose"
	"bread_robo_pose"
	"bread_russianblack_pose"
	"bread_shortbread_pose"
	"breadmonster"
	blend "r_hand_grip" 0 12
	blendwidth 13
	fadein 0.2
	fadeout 0.2
	hidden
	realtime
}

$sequence "fa_idle" {
	"c_pyro_animations_anims\fa_idle.smd"
	activity "ACT_MELEE_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "fa_draw" {
	"c_pyro_animations_anims\fa_draw.smd"
	activity "ACT_MELEE_VM_DRAW" 1
	{ event 5004 1 "Weapon_FireAxe.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "fa_swing_a" {
	"c_pyro_animations_anims\fa_swing_a.smd"
	activity "ACT_MELEE_VM_HITCENTER" 2
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "fa_swing_b" {
	"c_pyro_animations_anims\fa_swing_b.smd"
	activity "ACT_MELEE_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "fa_swing_c" {
	"c_pyro_animations_anims\fa_swing_c.smd"
	activity "ACT_MELEE_VM_SWINGHARD" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "fg_draw" {
	"c_pyro_animations_anims\fg_draw.smd"
	activity "ACT_ITEM1_VM_DRAW" 1
	{ event 5004 1 "Weapon_FlareGun.Draw" }
	{ event 5004 8 "Weapon_FlareGun.Grab" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "fg_idle" {
	"c_pyro_animations_anims\fg_idle.smd"
	activity "ACT_ITEM1_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "fg_fire" {
	"c_pyro_animations_anims\fg_fire.smd"
	activity "ACT_ITEM1_VM_PRIMARYATTACK" 1
	{ event 5004 24 "Weapon_FlareGun.TubeOpen" }
	{ event 5004 30 "Weapon_FlareGun.Reload" }
	{ event 5004 47 "Weapon_FlareGun.TubeCloseStart" }
	{ event 5004 49 "Weapon_FlareGun.TubeCloseFinish" }
	{ event AE_CL_BODYGROUP_SET_VALUE_CMODEL_WPN 26 "shell 1" }
	{ event AE_CL_BODYGROUP_SET_VALUE_CMODEL_WPN 36 "shell 0" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "ft_idle" {
	"c_pyro_animations_anims\ft_idle.smd"
	activity "ACT_PRIMARY_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "ft_fire" {
	"c_pyro_animations_anims\ft_fire.smd"
	activity "ACT_PRIMARY_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "ft_draw" {
	"c_pyro_animations_anims\ft_draw.smd"
	activity "ACT_PRIMARY_VM_DRAW" 1
	{ event 5004 1 "Weapon_FlameThrower.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "ft_alt_fire" {
	"c_pyro_animations_anims\ft_alt_fire.smd"
	activity "ACT_PRIMARY_VM_SECONDARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
}

$sequence "df_idle" {
	"c_pyro_animations_anims\df_idle.smd"
	activity "ACT_PRIMARY_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "df_fire" {
	"c_pyro_animations_anims\df_fire.smd"
	activity "ACT_PRIMARY_VM_PRIMARYATTACK_3" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "draw" {
	"c_pyro_animations_anims\draw.smd"
	activity "ACT_SECONDARY_VM_DRAW" 1
	{ event 5004 1 "Weapon_ShotgunPyro.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "idle" {
	"c_pyro_animations_anims\idle.smd"
	activity "ACT_SECONDARY_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "fire" {
	"c_pyro_animations_anims\fire.smd"
	activity "ACT_SECONDARY_VM_PRIMARYATTACK" 1
	{ event 5004 7 "Weapon_ShotgunEngineer.Cock_Back" }
	{ event 5004 12 "Weapon_ShotgunEngineer.Cock_Forward" }
	{ event 6002 13 "2" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "reload_start" {
	"c_pyro_animations_anims\reload_start.smd"
	activity "ACT_SECONDARY_RELOAD_START" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "reload_loop" {
	"c_pyro_animations_anims\reload_loop.smd"
	activity "ACT_SECONDARY_VM_RELOAD" 1
	{ event 5004 1 "Weapon_Shotgun.Reload" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "reload_end" {
	"c_pyro_animations_anims\reload_end.smd"
	activity "ACT_SECONDARY_RELOAD_FINISH" 1
	{ event 5004 12 "Weapon_ShotgunEngineer.Cock_Back" }
	{ event 5004 16 "Weapon_ShotgunEngineer.Cock_Forward" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "melee_allclass_draw" {
	"c_pyro_animations_anims\melee_allclass_draw.smd"
	activity "ACT_MELEE_ALLCLASS_VM_DRAW" 1
	{ event 5004 1 "Weapon_Machete.Draw" }
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	snap
	fps 30
}

$sequence "melee_allclass_idle" {
	"c_pyro_animations_anims\melee_allclass_idle.smd"
	activity "ACT_MELEE_ALLCLASS_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	fps 30
	loop
}

$sequence "melee_allclass_swing" {
	"c_pyro_animations_anims\melee_allclass_swing.smd"
	activity "ACT_MELEE_ALLCLASS_VM_HITCENTER" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	fps 30
}

$sequence "mm_draw" {
	"c_pyro_animations_anims\mm_draw.smd"
	activity "ACT_SECONDARY2_VM_DRAW" 1
	{ event 5004 1 "Weapon_FlareGun.Draw" }
	{ event 5004 8 "Weapon_FlareGun.Grab" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "mm_idle" {
	"c_pyro_animations_anims\mm_idle.smd"
	activity "ACT_SECONDARY2_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "mm_fire" {
	"c_pyro_animations_anims\mm_fire.smd"
	activity "ACT_SECONDARY2_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "throw_draw" {
	"c_pyro_animations_anims\throw_draw.smd"
	activity "ACT_THROWABLE_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	snap
	fps 30
}

$sequence "throw_idle" {
	"c_pyro_animations_anims\throw_idle.smd"
	activity "ACT_THROWABLE_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	node "raised"
	fps 30
	loop
}

$sequence "throw_fire" {
	"c_pyro_animations_anims\throw_fire.smd"
	activity "ACT_THROWABLE_VM_FIRE" 1
	fadein 0.2
	fadeout 0.2
	blendlayer "r_handposes" 0 0 0 0 local
	snap
	fps 30
}

$sequence "spell_draw" {
	"c_pyro_animations_anims\spell_draw.smd"
	activity "ACT_SPELL_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "spell_fire" {
	"c_pyro_animations_anims\spell_fire.smd"
	activity "ACT_SPELL_VM_FIRE" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "slap_draw" {
	"c_pyro_animations_anims\slap_draw.smd"
	activity "ACT_ITEM3_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 24
}

$sequence "slap_idle" {
	"c_pyro_animations_anims\slap_idle.smd"
	activity "ACT_ITEM3_VM_IDLE" 5
	fadein 0.2
	fadeout 0.2
	fps 24
	loop
}

$sequence "slap_idle2" {
	"c_pyro_animations_anims\slap_idle2.smd"
	activity "ACT_ITEM3_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 24
}

$sequence "slap" {
	"c_pyro_animations_anims\slap.smd"
	activity "ACT_ITEM3_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 24
}

$sequence "slap3" {
	"c_pyro_animations_anims\slap3.smd"
	activity "ACT_ITEM3_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 24
}

$sequence "slap2" {
	"c_pyro_animations_anims\slap2.smd"
	activity "ACT_ITEM3_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 24
}

$sequence "rocketpack_draw" {
	"c_pyro_animations_anims\rocketpack_draw.smd"
	activity "ACT_ITEM4_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 24
}

$sequence "rocketpack_idle" {
	"c_pyro_animations_anims\rocketpack_idle.smd"
	activity "ACT_ITEM4_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 24
	loop
}

$sequence "rocketpack_idle2" {
	"c_pyro_animations_anims\rocketpack_idle2.smd"
	activity "ACT_ITEM4_VM_PRIMARYATTACK" 1
	fadein 0.2
	fadeout 0.2
	fps 24
}

$sequence "rocketpack_holster" {
	"c_pyro_animations_anims\rocketpack_holster.smd"
	activity "ACT_ITEM4_VM_HOLSTER" 1
	fadein 0.2
	fadeout 0.2
	fps 28
}

$sequence "gascan_draw" {
	"c_pyro_animations_anims\gascan_draw.smd"
	activity "ACT_ITEM2_VM_DRAW" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "gascan_idle" {
	"c_pyro_animations_anims\gascan_idle.smd"
	activity "ACT_ITEM2_VM_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "gascan_fire" {
	"c_pyro_animations_anims\gascan_fire.smd"
	activity "ACT_ITEM2_VM_FIRE" 1
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "primary_inspect_start" {
	"c_pyro_animations_anims\primary_inspect_start.smd"
	activity "ACT_PRIMARY_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 26
}

$sequence "primary_inspect_idle" {
	"c_pyro_animations_anims\primary_inspect_idle.smd"
	activity "ACT_PRIMARY_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "primary_inspect_end" {
	"c_pyro_animations_anims\primary_inspect_end.smd"
	activity "ACT_PRIMARY_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement2" }
	{ event 5004 95 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "primary_alt1_inspect_start" {
	"c_pyro_animations_anims\primary_alt1_inspect_start.smd"
	activity "ACT_PRIMARY_ALT1_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 26
}

$sequence "primary_alt1_inspect_idle" {
	"c_pyro_animations_anims\primary_alt1_inspect_idle.smd"
	activity "ACT_PRIMARY_ALT1_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "primary_alt1_inspect_end" {
	"c_pyro_animations_anims\primary_alt1_inspect_end.smd"
	activity "ACT_PRIMARY_ALT1_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement2" }
	{ event 5004 95 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "secondary_inspect_start" {
	"c_pyro_animations_anims\secondary_inspect_start.smd"
	activity "ACT_SECONDARY_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "secondary_inspect_idle" {
	"c_pyro_animations_anims\secondary_inspect_idle.smd"
	activity "ACT_SECONDARY_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "secondary_inspect_end" {
	"c_pyro_animations_anims\secondary_inspect_end.smd"
	activity "ACT_SECONDARY_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement2" }
	{ event 5004 73 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "item1_inspect_start" {
	"c_pyro_animations_anims\item1_inspect_start.smd"
	activity "ACT_ITEM1_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "item1_inspect_idle" {
	"c_pyro_animations_anims\item1_inspect_idle.smd"
	activity "ACT_ITEM1_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "item1_inspect_end" {
	"c_pyro_animations_anims\item1_inspect_end.smd"
	activity "ACT_ITEM1_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement2" }
	{ event 5004 60 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "melee_inspect_start" {
	"c_pyro_animations_anims\melee_inspect_start.smd"
	activity "ACT_MELEE_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "melee_inspect_idle" {
	"c_pyro_animations_anims\melee_inspect_idle.smd"
	activity "ACT_MELEE_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "melee_inspect_end" {
	"c_pyro_animations_anims\melee_inspect_end.smd"
	activity "ACT_MELEE_VM_INSPECT_END" 1
	{ event 5004 4 "WeaponInspect.Movement3" }
	{ event 5004 70 "WeaponInspect.Movement2" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "melee_allclass_inspect_start" {
	"c_pyro_animations_anims\melee_allclass_inspect_start.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "melee_allclass_inspect_idle" {
	"c_pyro_animations_anims\melee_allclass_inspect_idle.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "melee_allclass_inspect_end" {
	"c_pyro_animations_anims\melee_allclass_inspect_end.smd"
	activity "ACT_MELEE_ALLCLASS_VM_INSPECT_END" 1
	{ event 5004 4 "WeaponInspect.Movement3" }
	{ event 5004 70 "WeaponInspect.Movement2" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "item2_inspect_start" {
	"c_pyro_animations_anims\item2_inspect_start.smd"
	activity "ACT_ITEM2_VM_INSPECT_START" 1
	{ event 5004 1 "Weapon_GasCan.InspectMovement1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "item2_inspect_idle" {
	"c_pyro_animations_anims\item2_inspect_idle.smd"
	activity "ACT_ITEM2_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "item2_inspect_end" {
	"c_pyro_animations_anims\item2_inspect_end.smd"
	activity "ACT_ITEM2_VM_INSPECT_END" 1
	{ event 5004 4 "Weapon_GasCan.InspectMovement2" }
	{ event 5004 68 "Weapon_GasCan.InspectMovement3" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "item3_inspect_start" {
	"c_pyro_animations_anims\item3_inspect_start.smd"
	activity "ACT_ITEM3_VM_INSPECT_START" 1
	{ event 5004 1 "MeleeInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "item3_inspect_idle" {
	"c_pyro_animations_anims\item3_inspect_idle.smd"
	activity "ACT_ITEM3_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "item3_inspect_end" {
	"c_pyro_animations_anims\item3_inspect_end.smd"
	activity "ACT_ITEM3_VM_INSPECT_END" 1
	{ event 5004 91 "MeleeInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "grapple_draw" {
	"c_pyro_animations_anims\grapple_draw.smd"
	activity "ACT_GRAPPLE_DRAW" 1
	{ event AE_CL_PLAYSOUND 1 "WeaponGrapplingHook.Draw" }
	fadein 0.2
	fadeout 0.2
	node "raised"
	snap
	fps 30
}

$sequence "grapple_idle" {
	"c_pyro_animations_anims\grapple_idle.smd"
	activity "ACT_GRAPPLE_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "grapple_fire_start" {
	"c_pyro_animations_anims\grapple_fire_start.smd"
	activity "ACT_GRAPPLE_FIRE_START" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "grapple_fire_idle" {
	"c_pyro_animations_anims\grapple_fire_idle.smd"
	activity "ACT_GRAPPLE_FIRE_IDLE" 1
	fadein 0.2
	fadeout 0.2
	node "raised"
	fps 30
	loop
}

$sequence "grapple_pull_start" {
	"c_pyro_animations_anims\grapple_pull_start.smd"
	activity "ACT_GRAPPLE_PULL_START" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "grapple_pull_idle" {
	"c_pyro_animations_anims\grapple_pull_idle.smd"
	activity "ACT_GRAPPLE_PULL_IDLE" 1
	fadein 0.1
	fadeout 0.2
	fps 30
	loop
}

$sequence "grapple_pull_end" {
	"c_pyro_animations_anims\grapple_pull_end.smd"
	activity "ACT_GRAPPLE_PULL_END" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_pickup" {
	"c_pyro_animations_anims\PASSTIME_ball_pickup.smd"
	activity "ACT_BALL_VM_PICKUP" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_idle" {
	"c_pyro_animations_anims\PASSTIME_ball_idle.smd"
	activity "ACT_BALL_VM_IDLE" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_catch1" {
	"c_pyro_animations_anims\PASSTIME_ball_catch1.smd"
	activity "ACT_BALL_VM_CATCH" 100
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_catch2" {
	"c_pyro_animations_anims\PASSTIME_ball_catch2.smd"
	activity "ACT_BALL_VM_CATCH" 1
	{ event AE_CL_PLAYSOUND 32 "Passtime.Throw" }
	{ event AE_CL_PLAYSOUND 55 "weapon.ImpactSoft" }
	{ event AE_CL_PLAYSOUND 75 "Pyro.GoodJob01" }
	{ event AE_CL_PLAYSOUND 115 "Pyro.Thanks01" }
	{ event AE_CL_PLAYSOUND 137 "Passtime.Throw" }
	{ event AE_CL_PLAYSOUND 165 "weapon.ImpactSoft" }
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_end" {
	"c_pyro_animations_anims\PASSTIME_ball_throw_end.smd"
	activity "ACT_BALL_VM_THROW_END" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_start" {
	"c_pyro_animations_anims\PASSTIME_ball_throw_start.smd"
	activity "ACT_BALL_VM_THROW_start" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "PASSTIME_ball_throw_loop" {
	"c_pyro_animations_anims\PASSTIME_ball_throw_loop.smd"
	activity "ACT_BALL_VM_THROW_LOOP" 1
	fadein 0.1
	fadeout 0.2
	fps 30
}

$sequence "dragons_fury_inspect_start" {
	"c_pyro_animations_anims\dragons_fury_inspect_start.smd"
	activity "ACT_ITEM4_VM_INSPECT_START" 1
	{ event 5004 1 "WeaponInspect.Movement3" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 26
}

$sequence "dragons_fury_inspect_idle" {
	"c_pyro_animations_anims\dragons_fury_inspect_idle.smd"
	activity "ACT_ITEM4_VM_INSPECT_IDLE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "dragons_fury_inspect_end" {
	"c_pyro_animations_anims\dragons_fury_inspect_end.smd"
	activity "ACT_ITEM4_VM_INSPECT_END" 1
	{ event 5004 1 "WeaponInspect.Movement2" }
	{ event 5004 95 "WeaponInspect.Movement4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}
